const mongoose = require('mongoose');
const dotenv = require('dotenv');
const User = require('../models/user.model');
const Product = require('../models/product.model');

dotenv.config();

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/p1';

const sampleUsers = [
  {
    name: 'Admin User',
    email: 'admin@grocery.com',
    password: 'Password@123',
    role: 'admin',
    isEmailVerified: true,
    phone: '+91 9876543210',
  },
  {
    name: 'John Doe',
    email: 'user@grocery.com',
    password: 'Password@123',
    role: 'user',
    isEmailVerified: true,
    phone: '+91 9876543211',
  },
];

const sampleProducts = [
  // 1. ELECTRONICS & GADGETS
  {
    name: 'SonicBass True Wireless Noise-Cancelling Earbuds',
    slug: 'sonicbass-true-wireless-earbuds',
    description: 'Immersive ANC audio with up to 32 hours total playback, Bluetooth 5.3, instant pairing, and IPX5 water resistance.',
    price: 3499,
    discountPrice: 2499,
    stock: 85,
    brand: 'SonicAudio',
    category: 'Electronics & Gadgets',
    unit: '1 Pair (Case Included)',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 128,
    images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80'],
    tags: ['electronics', 'earbuds', 'audio', 'wireless', 'gadgets'],
  },
  {
    name: 'FitPulse Ultra AMOLED Smartwatch with SpO2',
    slug: 'fitpulse-ultra-amoled-smartwatch',
    description: '1.96" HD Curved Display, Bluetooth calling, 100+ sports modes, heart rate tracking, and 7-day battery life.',
    price: 4999,
    discountPrice: 2999,
    stock: 60,
    brand: 'FitPulse',
    category: 'Electronics & Gadgets',
    unit: '1 Unit',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.7,
    ratingCount: 94,
    images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80'],
    tags: ['smartwatch', 'fitness', 'electronics', 'wearable'],
  },
  {
    name: 'VoltCharge 20000mAh 22.5W Fast Charging Power Bank',
    slug: 'voltcharge-20000mah-power-bank',
    description: 'Dual Type-C PD input/output, charge 3 devices simultaneously with intelligent safety chip protection.',
    price: 2499,
    discountPrice: 1799,
    stock: 120,
    brand: 'VoltCharge',
    category: 'Electronics & Gadgets',
    unit: '1 Unit',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 210,
    images: ['https://images.unsplash.com/photo-1609592424083-d92e59e376bf?auto=format&fit=crop&w=800&q=80'],
    tags: ['powerbank', 'electronics', 'charger', 'gadgets'],
  },
  {
    name: 'BoomBeat Portable Waterproof Bluetooth Speaker 20W',
    slug: 'boombeat-portable-bluetooth-speaker',
    description: 'Deep bass stereo sound with RGB light lights, 15 hours continuous playtime, IPX7 waterproof body.',
    price: 2999,
    discountPrice: 1999,
    stock: 75,
    brand: 'BoomBeat',
    category: 'Electronics & Gadgets',
    unit: '1 Unit',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.6,
    ratingCount: 82,
    images: ['https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=800&q=80'],
    tags: ['speaker', 'bluetooth', 'audio', 'electronics'],
  },

  // 2. MOBILES & ACCESSORIES
  {
    name: 'Apex 5G Smartphone (8GB RAM, 128GB Storage, Silver)',
    slug: 'apex-5g-smartphone-128gb',
    description: 'Powered by Octa-core 5G Processor, 6.7" 120Hz Super AMOLED display, 64MP OIS AI Camera, and 5000mAh battery.',
    price: 24999,
    discountPrice: 19999,
    stock: 35,
    brand: 'Apex Tech',
    category: 'Mobiles & Accessories',
    unit: '1 Device',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 156,
    images: ['https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80'],
    tags: ['mobile', 'smartphone', '5g', 'electronics', 'tech'],
  },
  {
    name: 'MagGrip Magnetic Car Phone Holder Mount',
    slug: 'maggrip-magnetic-car-phone-holder',
    description: 'Ultra-strong N52 magnets for 360-degree rotation, fits all dashboard vents securely without slipping.',
    price: 999,
    discountPrice: 599,
    stock: 150,
    brand: 'MagGrip',
    category: 'Mobiles & Accessories',
    unit: '1 Mount',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.6,
    ratingCount: 88,
    images: ['https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?auto=format&fit=crop&w=800&q=80'],
    tags: ['mobile', 'car mount', 'accessories'],
  },
  {
    name: 'FastCharge 65W GaN Dual Type-C Wall Charger',
    slug: 'fastcharge-65w-gan-wall-charger',
    description: 'Next-gen GaN technology fast charges smartphones, tablets, and laptops up to 50% in just 25 minutes.',
    price: 1999,
    discountPrice: 1499,
    stock: 90,
    brand: 'VoltCharge',
    category: 'Mobiles & Accessories',
    unit: '1 Adapter',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 104,
    images: ['https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80'],
    tags: ['mobile', 'charger', 'fast charge', 'accessories'],
  },

  // 3. COLD DRINKS & JUICES
  {
    name: 'Chilled Classic Cola (Pack of 6 x 300ml)',
    slug: 'chilled-classic-cola-pack-of-6',
    description: 'Ice-chilled refreshing fizzy cola soft drink. Perfect companion for meals, parties, and movie nights.',
    price: 240,
    discountPrice: 199,
    stock: 200,
    brand: 'FizzCo',
    category: 'Cold Drinks & Juices',
    unit: '6 Can Pack (300ml each)',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 310,
    images: ['https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=800&q=80'],
    tags: ['cold drink', 'soda', 'cola', 'beverages'],
  },
  {
    name: 'Pulse Extreme Energy Drink (4 x 250ml)',
    slug: 'pulse-extreme-energy-drink-4pack',
    description: 'Vitalizes body and mind with B-vitamins, Taurine, and instant energy boost for long working days.',
    price: 480,
    discountPrice: 399,
    stock: 110,
    brand: 'Pulse Energy',
    category: 'Cold Drinks & Juices',
    unit: '4 Cans Pack',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.7,
    ratingCount: 142,
    images: ['https://images.unsplash.com/photo-1622543925917-763c34d1a86e?auto=format&fit=crop&w=800&q=80'],
    tags: ['energy drink', 'cold drink', 'beverages'],
  },
  {
    name: '100% Pure Cold-Pressed Orange Juice (1 Litre)',
    slug: 'pure-cold-pressed-orange-juice-1l',
    description: 'Rich in Vitamin C with natural fruit pulp. No added refined sugars, water, or artificial flavorings.',
    price: 199,
    discountPrice: 159,
    stock: 90,
    brand: 'JuiceCraft',
    category: 'Cold Drinks & Juices',
    unit: '1 Litre Bottle',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 75,
    images: ['https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=800&q=80'],
    tags: ['juice', 'cold drink', 'fresh', 'orange'],
  },
  {
    name: 'Chilled Cold Brew Hazelnut Coffee Can (250ml)',
    slug: 'chilled-cold-brew-hazelnut-coffee',
    description: 'Slow brewed Arabica coffee beans blended with smooth milk and rich hazelnut flavor.',
    price: 150,
    discountPrice: 129,
    stock: 130,
    brand: 'BrewCraft',
    category: 'Cold Drinks & Juices',
    unit: '250ml Can',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 96,
    images: ['https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=800&q=80'],
    tags: ['coffee', 'cold brew', 'beverages', 'cold drink'],
  },

  // 4. SNACKS & MUNCHIES
  {
    name: 'Crunchy Kettle Cooked Potato Chips (Party Combo Pack)',
    slug: 'crunchy-kettle-cooked-potato-chips-combo',
    description: 'Slow cooked extra crispy potato chips in Sea Salt, Cream & Onion, and Peri Peri flavors.',
    price: 220,
    discountPrice: 179,
    stock: 180,
    brand: 'SnackBites',
    category: 'Snacks & Munchies',
    unit: 'Pack of 3 (150g each)',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 220,
    images: ['https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=800&q=80'],
    tags: ['chips', 'snacks', 'munchies', 'party'],
  },
  {
    name: 'Artisan Dark Chocolate 75% Cocoa Bar',
    slug: 'artisan-dark-chocolate-75-cocoa',
    description: 'Rich single-origin Belgian cocoa roasted chocolate with smooth velvety texture and antioxidant benefits.',
    price: 299,
    discountPrice: 249,
    stock: 140,
    brand: 'ChocoCrafters',
    category: 'Snacks & Munchies',
    unit: '120g Bar',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 180,
    images: ['https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&w=800&q=80'],
    tags: ['chocolate', 'dark chocolate', 'gourmet', 'snacks'],
  },
  {
    name: 'Roasted Salted Almonds & Cashews Gourmet Mix (200g)',
    slug: 'roasted-salted-almonds-cashews-mix',
    description: 'Premium slow-roasted California almonds and whole cashews seasoned with Himalayan pink salt.',
    price: 450,
    discountPrice: 349,
    stock: 110,
    brand: 'NutriBites',
    category: 'Snacks & Munchies',
    unit: '200g Pouch',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 145,
    images: ['https://images.unsplash.com/photo-1599599810769-bcde5a160d32?auto=format&fit=crop&w=800&q=80'],
    tags: ['nuts', 'dry fruits', 'healthy snacks', 'almonds'],
  },

  // 5. FRUITS & VEGETABLES
  {
    name: 'Fresh Premium Organic Bananas (1 Dozen)',
    slug: 'fresh-premium-organic-bananas',
    description: 'Sweet, energy-packed organic farm bananas rich in potassium and daily dietary fibers.',
    price: 89,
    discountPrice: 69,
    stock: 250,
    brand: 'Organic Farm',
    category: 'Fruits & Vegetables',
    unit: '1 Dozen (12 pcs)',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 420,
    images: ['https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=800&q=80'],
    tags: ['fruits', 'banana', 'organic', 'grocery'],
  },
  {
    name: 'Hass Avocados Imported (Pack of 4)',
    slug: 'hass-avocados-imported-pack-of-4',
    description: 'Creamy and rich Hass avocados. Perfect for breakfast toast, guacamole dip, and healthy salads.',
    price: 499,
    discountPrice: 399,
    stock: 90,
    brand: 'Green Harvest',
    category: 'Fruits & Vegetables',
    unit: 'Pack of 4 Pcs',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.7,
    ratingCount: 65,
    images: ['https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=800&q=80'],
    tags: ['avocado', 'vegetables', 'superfood', 'healthy'],
  },
  {
    name: 'Fresh Red Vine Tomatoes (1kg)',
    slug: 'fresh-red-vine-tomatoes-1kg',
    description: 'Farm-fresh juicy red tomatoes packed with Vitamin C and Lycopene. Handpicked from local greenhouses.',
    price: 65,
    discountPrice: 49,
    stock: 300,
    brand: 'Green Harvest',
    category: 'Fruits & Vegetables',
    unit: '1 kg Pack',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 280,
    images: ['https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=800&q=80'],
    tags: ['tomatoes', 'vegetables', 'fresh', 'farm'],
  },

  // 6. DAIRY & EGGS
  {
    name: 'Farm Fresh Toned Milk (1 Litre Pack)',
    slug: 'farm-fresh-toned-milk-1l',
    description: 'Pasteurized, homogenized pure fresh milk rich in calcium and essential vitamins for the family.',
    price: 75,
    discountPrice: 66,
    stock: 300,
    brand: 'Dairy Pure',
    category: 'Dairy & Eggs',
    unit: '1 Litre Pouch',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 510,
    images: ['https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=800&q=80'],
    tags: ['milk', 'dairy', 'fresh', 'calcium'],
  },
  {
    name: 'Farm Fresh Organic Brown Eggs (Pack of 12)',
    slug: 'farm-fresh-organic-brown-eggs-12pack',
    description: 'Free-range brown eggs rich in Omega-3 and protein. Sourced from humanely raised cage-free hens.',
    price: 149,
    discountPrice: 119,
    stock: 160,
    brand: 'Organic Farm',
    category: 'Dairy & Eggs',
    unit: 'Pack of 12 Eggs',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 230,
    images: ['https://images.unsplash.com/photo-1506976785307-8732e854ad03?auto=format&fit=crop&w=800&q=80'],
    tags: ['eggs', 'dairy', 'protein', 'organic'],
  },
  {
    name: 'Traditional Pure Cow Ghee (500ml Jar)',
    slug: 'traditional-pure-cow-ghee-500ml',
    description: 'Made using traditional Bilona method with golden granular texture and authentic rich aroma.',
    price: 599,
    discountPrice: 499,
    stock: 95,
    brand: 'Dairy Pure',
    category: 'Dairy & Eggs',
    unit: '500ml Glass Jar',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 180,
    images: ['https://images.unsplash.com/photo-1631451095765-2c91616fc9e6?auto=format&fit=crop&w=800&q=80'],
    tags: ['ghee', 'dairy', 'purity', 'cooking'],
  },

  // 7. PERSONAL CARE & BEAUTY
  {
    name: 'GlowSkin Vitamin C Hydrating Face Wash (150ml)',
    slug: 'glowskin-vitamin-c-hydrating-face-wash',
    description: 'Dermatologically tested facial cleanser with Vitamin C & Niacinamide for instant skin brightening.',
    price: 399,
    discountPrice: 299,
    stock: 110,
    brand: 'GlowSkin',
    category: 'Personal Care & Beauty',
    unit: '150ml Pump Bottle',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 112,
    images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80'],
    tags: ['beauty', 'skincare', 'face wash', 'personal care'],
  },
  {
    name: 'Activated Charcoal Deep Cleanse Shampoo (300ml)',
    slug: 'activated-charcoal-deep-cleanse-shampoo',
    description: 'Removes scalp impurities, excess oil, and product buildup. Enriched with Argan oil for silky smooth hair.',
    price: 449,
    discountPrice: 349,
    stock: 80,
    brand: 'HerbalPure',
    category: 'Personal Care & Beauty',
    unit: '300ml Bottle',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.7,
    ratingCount: 78,
    images: ['https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=800&q=80'],
    tags: ['shampoo', 'haircare', 'charcoal', 'personal care'],
  },

  // 8. HOME & KITCHEN
  {
    name: 'ProChef Non-Stick Die-Cast Frying Pan (26cm)',
    slug: 'prochef-non-stick-frying-pan-26cm',
    description: 'Heavy duty 5-layer granite coating, induction compatible base with ergonomic soft-touch handle.',
    price: 1899,
    discountPrice: 1299,
    stock: 45,
    brand: 'ProChef',
    category: 'Home & Kitchen',
    unit: '1 Pan',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.7,
    ratingCount: 58,
    images: ['https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80'],
    tags: ['kitchen', 'cookware', 'home', 'nonstick'],
  },
  {
    name: 'Stainless Steel Insulated Vacuum Water Bottle (1 Litre)',
    slug: 'stainless-steel-insulated-vacuum-water-bottle-1l',
    description: 'Keeps drinks ice cold for 24 hours or hot for 12 hours. BPA-free leakproof lid for office & gym.',
    price: 999,
    discountPrice: 699,
    stock: 140,
    brand: 'HydroSteel',
    category: 'Home & Kitchen',
    unit: '1 Bottle',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 165,
    images: ['https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=800&q=80'],
    tags: ['water bottle', 'kitchen', 'home', 'insulated'],
  },

  // 9. BAKERY
  {
    name: 'Artisan Whole Wheat Garlic Bread Loaf (400g)',
    slug: 'artisan-whole-wheat-garlic-bread-loaf',
    description: 'Freshly baked whole grain loaf infused with roasted garlic, herbs, and pure butter crust.',
    price: 99,
    discountPrice: 79,
    stock: 65,
    brand: 'BakeHouse',
    category: 'Bakery',
    unit: '400g Loaf',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.7,
    ratingCount: 92,
    images: ['https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80'],
    tags: ['bread', 'bakery', 'garlic bread', 'fresh'],
  },

  // 10. PANTRY & OIL
  {
    name: 'Extra Virgin Cold Pressed Olive Oil (750ml)',
    slug: 'extra-virgin-cold-pressed-olive-oil-750ml',
    description: 'First cold-pressed Mediterranean olive oil rich in antioxidants and healthy monounsaturated fats.',
    price: 1199,
    discountPrice: 899,
    stock: 70,
    brand: 'Mediterraneo',
    category: 'Pantry & Oil',
    unit: '750ml Glass Bottle',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 195,
    images: ['https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=800&q=80'],
    tags: ['olive oil', 'pantry', 'cooking', 'healthy'],
  },
];

async function seedDatabase() {
  try {
    console.log('Connecting to MongoDB...');
    await mongoose.connect(MONGODB_URI);
    console.log('Connected to MongoDB.');

    console.log('Clearing old users and products...');
    await User.deleteMany({});
    await Product.deleteMany({});

    console.log('Creating initial users...');
    const createdUsers = await User.create(sampleUsers);
    const adminUser = createdUsers.find((u) => u.role === 'admin');

    console.log(`Admin user created: ${adminUser.email}`);

    console.log('Creating initial products...');
    const productsToInsert = sampleProducts.map((p) => ({
      ...p,
      createdBy: adminUser._id,
    }));

    await Product.create(productsToInsert);
    console.log(`Successfully seeded ${productsToInsert.length} multi-category products!`);

    console.log('\n--- SEED COMPLETE ---');
    console.log('Admin Login: admin@grocery.com / Password@123');
    console.log('User Login: user@grocery.com / Password@123');
    console.log('--------------------\n');

    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
}

seedDatabase();
