const mongoose = require('mongoose');
const dotenv = require('dotenv');
const User = require('../models/user.model');
const Product = require('../models/product.model');

const path = require('path');
dotenv.config({ path: path.resolve(__dirname, '../.env') });

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/p1';

const sampleUsers = [
  {
    name: 'Admin User',
    email: 'admin@grocery.com',
    password: 'Password@123',
    role: 'admin',
    isEmailVerified: true,
    phone: '+91 9876543210',
  },
  {
    name: 'John Doe',
    email: 'user@grocery.com',
    password: 'Password@123',
    role: 'user',
    isEmailVerified: true,
    phone: '+91 9876543211',
  },
];

const sampleProducts = [
  // -------------------------------------------------------------
  // 1. ELECTRONICS & GADGETS (10 Products)
  // -------------------------------------------------------------
  {
    name: 'SonicBass True Wireless Noise-Cancelling Earbuds',
    slug: 'sonicbass-true-wireless-earbuds',
    description: 'Immersive ANC audio with up to 32 hours total playback, Bluetooth 5.3, instant pairing, and IPX5 water resistance.',
    price: 3499,
    discountPrice: 2499,
    stock: 85,
    brand: 'SonicAudio',
    category: 'Electronics & Gadgets',
    unit: '1 Pair (Case Included)',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 128,
    images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80'],
    tags: ['electronics', 'earbuds', 'audio', 'wireless', 'gadgets'],
  },
  {
    name: 'FitPulse Ultra AMOLED Smartwatch with SpO2',
    slug: 'fitpulse-ultra-amoled-smartwatch',
    description: '1.96" HD Curved Display, Bluetooth calling, 100+ sports modes, heart rate tracking, and 7-day battery life.',
    price: 4999,
    discountPrice: 2999,
    stock: 60,
    brand: 'FitPulse',
    category: 'Electronics & Gadgets',
    unit: '1 Unit',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.7,
    ratingCount: 94,
    images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80'],
    tags: ['smartwatch', 'fitness', 'electronics', 'wearable'],
  },
  {
    name: 'VoltCharge 20000mAh 22.5W Fast Charging Power Bank',
    slug: 'voltcharge-20000mah-power-bank',
    description: 'Dual Type-C PD input/output, charge 3 devices simultaneously with intelligent safety chip protection.',
    price: 2499,
    discountPrice: 1799,
    stock: 120,
    brand: 'VoltCharge',
    category: 'Electronics & Gadgets',
    unit: '1 Unit',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 210,
    images: ['https://images.unsplash.com/photo-1609592424083-d92e59e376bf?auto=format&fit=crop&w=800&q=80'],
    tags: ['powerbank', 'electronics', 'charger', 'gadgets'],
  },
  {
    name: 'BoomBeat Portable Waterproof Bluetooth Speaker 20W',
    slug: 'boombeat-portable-bluetooth-speaker',
    description: 'Deep bass stereo sound with RGB lighting effects, 15 hours continuous playtime, IPX7 waterproof body.',
    price: 2999,
    discountPrice: 1999,
    stock: 75,
    brand: 'BoomBeat',
    category: 'Electronics & Gadgets',
    unit: '1 Unit',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.6,
    ratingCount: 82,
    images: ['https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=800&q=80'],
    tags: ['speaker', 'bluetooth', 'audio', 'electronics'],
  },
  {
    name: 'LuminaRGB Folding Desk Lamp with Wireless Phone Charger',
    slug: 'luminargb-folding-desk-lamp',
    description: 'Smart touch dimmable LED desk lamp with 3 color temperatures, eye-care technology, and 10W wireless charging pad.',
    price: 1899,
    discountPrice: 1399,
    stock: 50,
    brand: 'Lumina',
    category: 'Electronics & Gadgets',
    unit: '1 Lamp',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.6,
    ratingCount: 45,
    images: ['https://images.unsplash.com/photo-1534073828943-f801091bb18c?auto=format&fit=crop&w=800&q=80'],
    tags: ['lamp', 'desk lamp', 'electronics', 'wireless charger'],
  },
  {
    name: 'ClearSound Studio Over-Ear Wireless Headphones',
    slug: 'clearsound-studio-over-ear-headphones',
    description: '40mm titanium drivers deliver rich acoustic performance with memory foam ear cushions and 40-hr battery.',
    price: 5999,
    discountPrice: 3999,
    stock: 40,
    brand: 'SonicAudio',
    category: 'Electronics & Gadgets',
    unit: '1 Unit',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 115,
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80'],
    tags: ['headphones', 'audio', 'wireless', 'electronics'],
  },
  {
    name: 'HyperGlide Ergonomic RGB Wireless Gaming Mouse',
    slug: 'hyperglide-ergonomic-gaming-mouse',
    description: '16,000 DPI optical sensor, ultra-low latency 2.4GHz wireless connection, 6 programmable macro buttons.',
    price: 2199,
    discountPrice: 1499,
    stock: 90,
    brand: 'HyperGlide',
    category: 'Electronics & Gadgets',
    unit: '1 Unit',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.7,
    ratingCount: 68,
    images: ['https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=800&q=80'],
    tags: ['mouse', 'gaming', 'electronics', 'gadgets'],
  },
  {
    name: 'Type-C Multi-Port 7-in-1 Aluminum Hub Adapter',
    slug: 'type-c-multiport-7-in-1-hub',
    description: 'Expand your laptop with 4K HDMI, 100W PD pass-through charging, SD/TF card reader, and 3 x USB 3.0 ports.',
    price: 2299,
    discountPrice: 1599,
    stock: 110,
    brand: 'VoltCharge',
    category: 'Electronics & Gadgets',
    unit: '1 Hub',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 140,
    images: ['https://images.unsplash.com/photo-1544652478-6653e09f18a2?auto=format&fit=crop&w=800&q=80'],
    tags: ['adapter', 'hub', 'type-c', 'electronics'],
  },
  {
    name: 'VisionCam 1080p Full HD Webcam with Built-in Microphone',
    slug: 'visioncam-1080p-full-hd-webcam',
    description: 'Plug-and-play USB webcam with auto light correction, noise-reducing dual mics, and privacy shutter.',
    price: 1999,
    discountPrice: 1299,
    stock: 65,
    brand: 'VisionCam',
    category: 'Electronics & Gadgets',
    unit: '1 Camera',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.5,
    ratingCount: 52,
    images: ['https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80'],
    tags: ['webcam', 'video', 'electronics', 'camera'],
  },
  {
    name: 'UltraTab 10.1 Inch HD Android Tablet with Stylus',
    slug: 'ultratab-10-inch-hd-android-tablet',
    description: 'Octa-core processor, 4GB RAM, 64GB expandable storage, dual stereo speakers, and pen stylus support.',
    price: 12999,
    discountPrice: 9999,
    stock: 30,
    brand: 'Apex Tech',
    category: 'Electronics & Gadgets',
    unit: '1 Tablet',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.7,
    ratingCount: 88,
    images: ['https://images.unsplash.com/photo-1561154464-82e9adf32764?auto=format&fit=crop&w=800&q=80'],
    tags: ['tablet', 'android', 'electronics', 'gadgets'],
  },

  // -------------------------------------------------------------
  // 2. MOBILES & ACCESSORIES (10 Products)
  // -------------------------------------------------------------
  {
    name: 'Apex 5G Smartphone (8GB RAM, 128GB Storage, Silver)',
    slug: 'apex-5g-smartphone-128gb',
    description: 'Powered by Octa-core 5G Processor, 6.7" 120Hz Super AMOLED display, 64MP OIS AI Camera, and 5000mAh battery.',
    price: 24999,
    discountPrice: 19999,
    stock: 35,
    brand: 'Apex Tech',
    category: 'Mobiles & Accessories',
    unit: '1 Device',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 156,
    images: ['https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80'],
    tags: ['mobile', 'smartphone', '5g', 'electronics', 'tech'],
  },
  {
    name: 'MagGrip Magnetic Car Phone Holder Mount',
    slug: 'maggrip-magnetic-car-phone-holder',
    description: 'Ultra-strong N52 magnets for 360-degree rotation, fits all dashboard vents securely without slipping.',
    price: 999,
    discountPrice: 599,
    stock: 150,
    brand: 'MagGrip',
    category: 'Mobiles & Accessories',
    unit: '1 Mount',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.6,
    ratingCount: 88,
    images: ['https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?auto=format&fit=crop&w=800&q=80'],
    tags: ['mobile', 'car mount', 'accessories'],
  },
  {
    name: 'FastCharge 65W GaN Dual Type-C Wall Charger',
    slug: 'fastcharge-65w-gan-wall-charger',
    description: 'Next-gen GaN technology fast charges smartphones, tablets, and laptops up to 50% in just 25 minutes.',
    price: 1999,
    discountPrice: 1499,
    stock: 90,
    brand: 'VoltCharge',
    category: 'Mobiles & Accessories',
    unit: '1 Adapter',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 104,
    images: ['https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80'],
    tags: ['mobile', 'charger', 'fast charge', 'accessories'],
  },
  {
    name: 'ShieldGlass 9H Tempered Glass Screen Protector (2 Pack)',
    slug: 'shieldglass-9h-tempered-glass-2pack',
    description: 'Ultra-clear 9H hardness shatterproof screen protector with oleophobic anti-fingerprint coating.',
    price: 499,
    discountPrice: 299,
    stock: 200,
    brand: 'ShieldGlass',
    category: 'Mobiles & Accessories',
    unit: '2 Pack',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.7,
    ratingCount: 190,
    images: ['https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?auto=format&fit=crop&w=800&q=80'],
    tags: ['screen protector', 'mobile', 'accessories'],
  },
  {
    name: 'ArmorFlex Heavy Duty Military Grade Anti-Drop Phone Case',
    slug: 'armorflex-heavy-duty-phone-case',
    description: 'Dual layer shockproof TPU + PC armor case with built-in kickstand and raised lens protection.',
    price: 899,
    discountPrice: 499,
    stock: 130,
    brand: 'ArmorFlex',
    category: 'Mobiles & Accessories',
    unit: '1 Case',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 76,
    images: ['https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?auto=format&fit=crop&w=800&q=80'],
    tags: ['case', 'cover', 'mobile', 'accessories'],
  },
  {
    name: 'FlexiStand Adjustable Metal Phone & Tablet Desktop Stand',
    slug: 'flexistand-adjustable-metal-desktop-stand',
    description: 'Heavy duty aluminum alloy desktop stand with anti-slip rubber pads and foldable design.',
    price: 799,
    discountPrice: 399,
    stock: 160,
    brand: 'FlexiStand',
    category: 'Mobiles & Accessories',
    unit: '1 Stand',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 145,
    images: ['https://images.unsplash.com/photo-1586953208448-b95a79798f07?auto=format&fit=crop&w=800&q=80'],
    tags: ['stand', 'mobile', 'accessories', 'desktop'],
  },
  {
    name: 'CrystalClear Magnetic Wireless Case for iPhone 15',
    slug: 'crystalclear-magnetic-case-iphone-15',
    description: 'Yellowing-resistant transparent magnetic case compatible with all wireless chargers and car mounts.',
    price: 1199,
    discountPrice: 699,
    stock: 95,
    brand: 'ArmorFlex',
    category: 'Mobiles & Accessories',
    unit: '1 Case',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 110,
    images: ['https://images.unsplash.com/photo-1541877944-ac82a091518a?auto=format&fit=crop&w=800&q=80'],
    tags: ['iphone', 'case', 'mobile', 'accessories'],
  },
  {
    name: 'Nylon Braided 100W Fast Charging Type-C Cable (2m)',
    slug: 'nylon-braided-100w-type-c-cable-2m',
    description: 'Tangle-free military-grade braided nylon cable supporting 100W PD charging and 480Mbps data transfer.',
    price: 599,
    discountPrice: 349,
    stock: 220,
    brand: 'VoltCharge',
    category: 'Mobiles & Accessories',
    unit: '1 Cable (2m)',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 230,
    images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80'],
    tags: ['cable', 'type-c', 'mobile', 'accessories'],
  },
  {
    name: 'Wireless Qi Fast Charging Pad 15W Slim Metal Base',
    slug: 'wireless-qi-fast-charging-pad-15w',
    description: 'Ultra-thin aluminum alloy fast wireless charging pad with foreign object detection and LED status light.',
    price: 1499,
    discountPrice: 899,
    stock: 80,
    brand: 'VoltCharge',
    category: 'Mobiles & Accessories',
    unit: '1 Charging Pad',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.7,
    ratingCount: 89,
    images: ['https://images.unsplash.com/photo-1622445268465-8438165a268e?auto=format&fit=crop&w=800&q=80'],
    tags: ['wireless charger', 'mobile', 'accessories'],
  },
  {
    name: 'Universal International Travel Adapter Dual USB',
    slug: 'universal-international-travel-adapter',
    description: 'All-in-one travel plug adapter supporting 150+ countries with built-in fuse safety protection.',
    price: 1299,
    discountPrice: 799,
    stock: 100,
    brand: 'VoltCharge',
    category: 'Mobiles & Accessories',
    unit: '1 Adapter',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 165,
    images: ['https://images.unsplash.com/photo-1563770660941-20978e870e26?auto=format&fit=crop&w=800&q=80'],
    tags: ['adapter', 'travel', 'mobile', 'accessories'],
  },

  // -------------------------------------------------------------
  // 3. COLD DRINKS & JUICES (10 Products)
  // -------------------------------------------------------------
  {
    name: 'Chilled Classic Cola (Pack of 6 x 300ml)',
    slug: 'chilled-classic-cola-pack-of-6',
    description: 'Ice-chilled refreshing fizzy cola soft drink. Perfect companion for meals, parties, and movie nights.',
    price: 240,
    discountPrice: 199,
    stock: 200,
    brand: 'FizzCo',
    category: 'Cold Drinks & Juices',
    unit: '6 Can Pack (300ml each)',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 310,
    images: ['https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=800&q=80'],
    tags: ['cold drink', 'soda', 'cola', 'beverages'],
  },
  {
    name: 'Pulse Extreme Energy Drink (4 x 250ml)',
    slug: 'pulse-extreme-energy-drink-4pack',
    description: 'Vitalizes body and mind with B-vitamins, Taurine, and instant energy boost for long working days.',
    price: 480,
    discountPrice: 399,
    stock: 110,
    brand: 'Pulse Energy',
    category: 'Cold Drinks & Juices',
    unit: '4 Cans Pack',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.7,
    ratingCount: 142,
    images: ['https://images.unsplash.com/photo-1622543925917-763c34d1a86e?auto=format&fit=crop&w=800&q=80'],
    tags: ['energy drink', 'cold drink', 'beverages'],
  },
  {
    name: '100% Pure Cold-Pressed Orange Juice (1 Litre)',
    slug: 'pure-cold-pressed-orange-juice-1l',
    description: 'Rich in Vitamin C with natural fruit pulp. No added refined sugars, water, or artificial flavorings.',
    price: 199,
    discountPrice: 159,
    stock: 90,
    brand: 'JuiceCraft',
    category: 'Cold Drinks & Juices',
    unit: '1 Litre Bottle',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 75,
    images: ['https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=800&q=80'],
    tags: ['juice', 'cold drink', 'fresh', 'orange'],
  },
  {
    name: 'Chilled Cold Brew Hazelnut Coffee Can (250ml)',
    slug: 'chilled-cold-brew-hazelnut-coffee',
    description: 'Slow brewed Arabica coffee beans blended with smooth milk and rich hazelnut flavor.',
    price: 150,
    discountPrice: 129,
    stock: 130,
    brand: 'BrewCraft',
    category: 'Cold Drinks & Juices',
    unit: '250ml Can',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 96,
    images: ['https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=800&q=80'],
    tags: ['coffee', 'cold brew', 'beverages', 'cold drink'],
  },
  {
    name: 'Sparkling Lemon Lime Refreshing Soda (6 x 330ml)',
    slug: 'sparkling-lemon-lime-soda-6pack',
    description: 'Zesty lemon-lime crisp soda made with carbonated spring water and natural citrus flavors.',
    price: 220,
    discountPrice: 179,
    stock: 180,
    brand: 'FizzCo',
    category: 'Cold Drinks & Juices',
    unit: '6 Can Pack',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.7,
    ratingCount: 130,
    images: ['https://images.unsplash.com/photo-1527661591475-527312dd65f5?auto=format&fit=crop&w=800&q=80'],
    tags: ['lemonade', 'soda', 'cold drink', 'beverages'],
  },
  {
    name: 'Fresh Alphonso Mango Pulp Juice Bottle (1 Litre)',
    slug: 'fresh-alphonso-mango-pulp-juice-1l',
    description: 'Made from handpicked Ratnagiri Alphonso mangoes. Rich thick nectar texture with authentic sweet aroma.',
    price: 180,
    discountPrice: 149,
    stock: 140,
    brand: 'JuiceCraft',
    category: 'Cold Drinks & Juices',
    unit: '1 Litre Bottle',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 240,
    images: ['https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=800&q=80'],
    tags: ['mango', 'juice', 'cold drink', 'beverages'],
  },
  {
    name: 'Hydrate Electrolyte Sports Energy Drink Orange (500ml)',
    slug: 'hydrate-electrolyte-sports-drink-500ml',
    description: 'Restores vital minerals lost during intense workouts, running, or outdoor summer activity.',
    price: 75,
    discountPrice: 59,
    stock: 210,
    brand: 'Pulse Energy',
    category: 'Cold Drinks & Juices',
    unit: '500ml Bottle',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.6,
    ratingCount: 88,
    images: ['https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80'],
    tags: ['sports drink', 'electrolyte', 'cold drink'],
  },
  {
    name: 'Pure Tender Coconut Water Tetra Pack (1 Litre)',
    slug: 'pure-tender-coconut-water-1l',
    description: 'Naturally hydrating 100% pure coconut water packed with potassium, zero cholesterol, and low calories.',
    price: 160,
    discountPrice: 129,
    stock: 160,
    brand: 'JuiceCraft',
    category: 'Cold Drinks & Juices',
    unit: '1 Litre Pack',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 195,
    images: ['https://images.unsplash.com/photo-1525385133512-2f3bdd039054?auto=format&fit=crop&w=800&q=80'],
    tags: ['coconut water', 'healthy', 'cold drink'],
  },
  {
    name: 'Chilled Iced Peach Green Tea Can (300ml)',
    slug: 'chilled-iced-peach-green-tea-300ml',
    description: 'Refreshing real brewed antioxidant-rich green tea infused with sweet peach juice flavor.',
    price: 99,
    discountPrice: 79,
    stock: 120,
    brand: 'BrewCraft',
    category: 'Cold Drinks & Juices',
    unit: '300ml Can',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.7,
    ratingCount: 110,
    images: ['https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=800&q=80'],
    tags: ['iced tea', 'green tea', 'cold drink', 'peach'],
  },
  {
    name: 'Zero Sugar Sparkling Fizzy Tonic Water (Pack of 4)',
    slug: 'zero-sugar-sparkling-tonic-water-4pack',
    description: 'Crisp premium mixer tonic water crafted with natural quinine and zero calories.',
    price: 280,
    discountPrice: 229,
    stock: 90,
    brand: 'FizzCo',
    category: 'Cold Drinks & Juices',
    unit: '4 Cans Pack',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 72,
    images: ['https://images.unsplash.com/photo-1581006852262-e4307cf6283a?auto=format&fit=crop&w=800&q=80'],
    tags: ['tonic water', 'zero sugar', 'cold drink'],
  },

  // -------------------------------------------------------------
  // 4. SNACKS & MUNCHIES (10 Products)
  // -------------------------------------------------------------
  {
    name: 'Crunchy Kettle Cooked Potato Chips (Party Combo Pack)',
    slug: 'crunchy-kettle-cooked-potato-chips-combo',
    description: 'Slow cooked extra crispy potato chips in Sea Salt, Cream & Onion, and Peri Peri flavors.',
    price: 220,
    discountPrice: 179,
    stock: 180,
    brand: 'SnackBites',
    category: 'Snacks & Munchies',
    unit: 'Pack of 3 (150g each)',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 220,
    images: ['https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=800&q=80'],
    tags: ['chips', 'snacks', 'munchies', 'party'],
  },
  {
    name: 'Artisan Dark Chocolate 75% Cocoa Bar (120g)',
    slug: 'artisan-dark-chocolate-75-cocoa',
    description: 'Rich single-origin Belgian cocoa roasted chocolate with smooth velvety texture and antioxidant benefits.',
    price: 299,
    discountPrice: 249,
    stock: 140,
    brand: 'ChocoCrafters',
    category: 'Snacks & Munchies',
    unit: '120g Bar',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 180,
    images: ['https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&w=800&q=80'],
    tags: ['chocolate', 'dark chocolate', 'gourmet', 'snacks'],
  },
  {
    name: 'Roasted Salted Almonds & Cashews Gourmet Mix (200g)',
    slug: 'roasted-salted-almonds-cashews-mix',
    description: 'Premium slow-roasted California almonds and whole cashews seasoned with Himalayan pink salt.',
    price: 450,
    discountPrice: 349,
    stock: 110,
    brand: 'NutriBites',
    category: 'Snacks & Munchies',
    unit: '200g Pouch',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 145,
    images: ['https://images.unsplash.com/photo-1599599810769-bcde5a160d32?auto=format&fit=crop&w=800&q=80'],
    tags: ['nuts', 'dry fruits', 'healthy snacks', 'almonds'],
  },
  {
    name: 'Spicy Peri Peri Nacho Chips with Cheese Dip (150g)',
    slug: 'spicy-peri-peri-nacho-chips-with-dip',
    description: 'Stone-ground corn nachos tossed in tangy spicy peri peri seasoning with a tray of creamy jalapeno cheese dip.',
    price: 140,
    discountPrice: 115,
    stock: 150,
    brand: 'SnackBites',
    category: 'Snacks & Munchies',
    unit: '150g Pack',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.7,
    ratingCount: 160,
    images: ['https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?auto=format&fit=crop&w=800&q=80'],
    tags: ['nachos', 'snacks', 'munchies', 'cheese'],
  },
  {
    name: 'Movie Theatre Style Butter Popcorn (100g)',
    slug: 'movie-theatre-butter-popcorn-100g',
    description: 'Freshly popped whole grain corn coated in golden rich melted butter and sea salt.',
    price: 99,
    discountPrice: 79,
    stock: 200,
    brand: 'SnackBites',
    category: 'Snacks & Munchies',
    unit: '100g Bag',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 210,
    images: ['https://images.unsplash.com/photo-1578849278619-e73505e9610f?auto=format&fit=crop&w=800&q=80'],
    tags: ['popcorn', 'butter', 'snacks', 'munchies'],
  },
  {
    name: 'Roasted Makhana Cream & Onion Healthy Snack (80g)',
    slug: 'roasted-makhana-cream-and-onion-80g',
    description: 'Slow roasted organic fox nuts tossed in creamy onion seasoning. High protein & low calorie guilt-free munching.',
    price: 180,
    discountPrice: 139,
    stock: 130,
    brand: 'NutriBites',
    category: 'Snacks & Munchies',
    unit: '80g Pack',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 175,
    images: ['https://images.unsplash.com/photo-1599599810694-b5b37304c03d?auto=format&fit=crop&w=800&q=80'],
    tags: ['makhana', 'healthy snacks', 'roasted'],
  },
  {
    name: 'Whole Wheat Crunchy Digestive Biscuits Box (300g)',
    slug: 'whole-wheat-digestive-biscuits-300g',
    description: 'Baked with high fiber whole grains and oats. Perfect evening tea-time snack for digestive wellness.',
    price: 120,
    discountPrice: 99,
    stock: 160,
    brand: 'BakeHouse',
    category: 'Snacks & Munchies',
    unit: '300g Box',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.6,
    ratingCount: 118,
    images: ['https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=800&q=80'],
    tags: ['biscuits', 'digestive', 'snacks', 'tea time'],
  },
  {
    name: 'Cheesy Cheddar Crispy Pretzel Twists (150g)',
    slug: 'cheesy-cheddar-crispy-pretzel-twists',
    description: 'Oven-baked crunchy pretzels drenched in real sharp cheddar cheese powder.',
    price: 160,
    discountPrice: 129,
    stock: 100,
    brand: 'SnackBites',
    category: 'Snacks & Munchies',
    unit: '150g Bag',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.7,
    ratingCount: 84,
    images: ['https://images.unsplash.com/photo-1528751014936-863e6e7a319c?auto=format&fit=crop&w=800&q=80'],
    tags: ['pretzels', 'cheese', 'snacks', 'munchies'],
  },
  {
    name: 'Organic Multigrain & Berry Energy Bars (Pack of 6)',
    slug: 'organic-multigrain-energy-bars-6pack',
    description: 'Packed with almonds, pumpkin seeds, cranberries, and raw honey. Zero added preservatives.',
    price: 360,
    discountPrice: 289,
    stock: 110,
    brand: 'NutriBites',
    category: 'Snacks & Munchies',
    unit: '6 Bars Box',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 135,
    images: ['https://images.unsplash.com/photo-1622484210800-096d2fa3c3f9?auto=format&fit=crop&w=800&q=80'],
    tags: ['energy bar', 'healthy', 'granola', 'snacks'],
  },
  {
    name: 'Jumbo Roasted & Salted Peanuts Pouch (250g)',
    slug: 'jumbo-roasted-salted-peanuts-250g',
    description: 'Golden roasted jumbo groundnuts seasoned with sea salt. Protein-packed crunch.',
    price: 110,
    discountPrice: 85,
    stock: 190,
    brand: 'NutriBites',
    category: 'Snacks & Munchies',
    unit: '250g Pouch',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.7,
    ratingCount: 140,
    images: ['https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&w=800&q=80'],
    tags: ['peanuts', 'nuts', 'snacks', 'munchies'],
  },

  // -------------------------------------------------------------
  // 5. FRUITS & VEGETABLES (10 Products)
  // -------------------------------------------------------------
  {
    name: 'Fresh Premium Organic Bananas (1 Dozen)',
    slug: 'fresh-premium-organic-bananas',
    description: 'Sweet, energy-packed organic farm bananas rich in potassium and daily dietary fibers.',
    price: 89,
    discountPrice: 69,
    stock: 250,
    brand: 'Organic Farm',
    category: 'Fruits & Vegetables',
    unit: '1 Dozen (12 pcs)',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 420,
    images: ['https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=800&q=80'],
    tags: ['fruits', 'banana', 'organic', 'grocery'],
  },
  {
    name: 'Hass Avocados Imported (Pack of 4)',
    slug: 'hass-avocados-imported-pack-of-4',
    description: 'Creamy and rich Hass avocados. Perfect for breakfast toast, guacamole dip, and healthy salads.',
    price: 499,
    discountPrice: 399,
    stock: 90,
    brand: 'Green Harvest',
    category: 'Fruits & Vegetables',
    unit: 'Pack of 4 Pcs',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.7,
    ratingCount: 65,
    images: ['https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=800&q=80'],
    tags: ['avocado', 'vegetables', 'superfood', 'healthy'],
  },
  {
    name: 'Fresh Red Vine Tomatoes (1kg)',
    slug: 'fresh-red-vine-tomatoes-1kg',
    description: 'Farm-fresh juicy red tomatoes packed with Vitamin C and Lycopene. Handpicked from local greenhouses.',
    price: 65,
    discountPrice: 49,
    stock: 300,
    brand: 'Green Harvest',
    category: 'Fruits & Vegetables',
    unit: '1 kg Pack',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 280,
    images: ['https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=800&q=80'],
    tags: ['tomatoes', 'vegetables', 'fresh', 'farm'],
  },
  {
    name: 'Crisp Sweet Shimla Red Apples (1kg Pack)',
    slug: 'crisp-sweet-shimla-red-apples-1kg',
    description: 'Orchard fresh juicy Shimla apples with high natural dietary fiber and refreshing sweet crunch.',
    price: 220,
    discountPrice: 179,
    stock: 180,
    brand: 'Green Harvest',
    category: 'Fruits & Vegetables',
    unit: '1 kg Pack (approx 5-6 pcs)',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 310,
    images: ['https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=800&q=80'],
    tags: ['apples', 'fruits', 'fresh', 'organic'],
  },
  {
    name: 'Farm Fresh Hydroponic Baby Spinach (250g)',
    slug: 'farm-fresh-hydroponic-baby-spinach-250g',
    description: 'Triple washed pesticide-free green baby spinach leaves. Rich in iron, folate, and Vitamin A.',
    price: 75,
    discountPrice: 55,
    stock: 140,
    brand: 'Green Harvest',
    category: 'Fruits & Vegetables',
    unit: '250g Pack',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 160,
    images: ['https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=800&q=80'],
    tags: ['spinach', 'vegetables', 'leafy greens', 'fresh'],
  },
  {
    name: 'Sweet Organic Red Strawberries Box (250g)',
    slug: 'sweet-organic-red-strawberries-250g',
    description: 'Juicy ruby red Mahabaleshwar strawberries. Perfect for desserts, smoothies, and snacking.',
    price: 180,
    discountPrice: 139,
    stock: 110,
    brand: 'Organic Farm',
    category: 'Fruits & Vegetables',
    unit: '250g Tray Box',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 225,
    images: ['https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=800&q=80'],
    tags: ['strawberries', 'fruits', 'berries', 'fresh'],
  },
  {
    name: 'Crunchy Imported Washington Gala Apples (1kg)',
    slug: 'crunchy-imported-washington-gala-apples-1kg',
    description: 'Crisp imported Gala apples with bright thin red skin and aromatic sweet nectar juice.',
    price: 280,
    discountPrice: 229,
    stock: 130,
    brand: 'Green Harvest',
    category: 'Fruits & Vegetables',
    unit: '1 kg Pack',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 140,
    images: ['https://images.unsplash.com/photo-1579613832111-ac7dfcc7723f?auto=format&fit=crop&w=800&q=80'],
    tags: ['apples', 'fruits', 'imported', 'fresh'],
  },
  {
    name: 'Sweet Seedless Green Grapes (500g)',
    slug: 'sweet-seedless-green-grapes-500g',
    description: 'Plump and crisp green grapes freshly harvested from Nashik vineyards. Bursting with natural sweetness.',
    price: 130,
    discountPrice: 99,
    stock: 170,
    brand: 'Green Harvest',
    category: 'Fruits & Vegetables',
    unit: '500g Pack',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.7,
    ratingCount: 195,
    images: ['https://images.unsplash.com/photo-1537640538966-79f369143f8f?auto=format&fit=crop&w=800&q=80'],
    tags: ['grapes', 'fruits', 'fresh', 'seedless'],
  },
  {
    name: 'Fresh White Button Mushrooms Tray (200g)',
    slug: 'fresh-white-button-mushrooms-200g',
    description: 'Firm, clean white button mushrooms cultivated under strict temperature-controlled hygienic environments.',
    price: 60,
    discountPrice: 45,
    stock: 200,
    brand: 'Green Harvest',
    category: 'Fruits & Vegetables',
    unit: '200g Pack',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 150,
    images: ['https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80'],
    tags: ['mushrooms', 'vegetables', 'fresh'],
  },
  {
    name: 'Sweet Golden Rani Pineapple (1 Whole)',
    slug: 'sweet-golden-rani-pineapple-1pc',
    description: 'Tropical golden ripe pineapple with high vitamin content and intense aromatic juice flavor.',
    price: 120,
    discountPrice: 89,
    stock: 90,
    brand: 'Organic Farm',
    category: 'Fruits & Vegetables',
    unit: '1 Whole Fruit',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.6,
    ratingCount: 82,
    images: ['https://images.unsplash.com/photo-1550258987-190a2d41a8ba?auto=format&fit=crop&w=800&q=80'],
    tags: ['pineapple', 'fruits', 'tropical', 'fresh'],
  },

  // -------------------------------------------------------------
  // 6. DAIRY & EGGS (10 Products)
  // -------------------------------------------------------------
  {
    name: 'Farm Fresh Toned Milk (1 Litre Pack)',
    slug: 'farm-fresh-toned-milk-1l',
    description: 'Pasteurized, homogenized pure fresh milk rich in calcium and essential vitamins for the family.',
    price: 75,
    discountPrice: 66,
    stock: 300,
    brand: 'Dairy Pure',
    category: 'Dairy & Eggs',
    unit: '1 Litre Pouch',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 510,
    images: ['https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=800&q=80'],
    tags: ['milk', 'dairy', 'fresh', 'calcium'],
  },
  {
    name: 'Farm Fresh Organic Brown Eggs (Pack of 12)',
    slug: 'farm-fresh-organic-brown-eggs-12pack',
    description: 'Free-range brown eggs rich in Omega-3 and protein. Sourced from humanely raised cage-free hens.',
    price: 149,
    discountPrice: 119,
    stock: 160,
    brand: 'Organic Farm',
    category: 'Dairy & Eggs',
    unit: 'Pack of 12 Eggs',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 230,
    images: ['https://images.unsplash.com/photo-1506976785307-8732e854ad03?auto=format&fit=crop&w=800&q=80'],
    tags: ['eggs', 'dairy', 'protein', 'organic'],
  },
  {
    name: 'Traditional Pure Cow Ghee (500ml Jar)',
    slug: 'traditional-pure-cow-ghee-500ml',
    description: 'Made using traditional Bilona method with golden granular texture and authentic rich aroma.',
    price: 599,
    discountPrice: 499,
    stock: 95,
    brand: 'Dairy Pure',
    category: 'Dairy & Eggs',
    unit: '500ml Glass Jar',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 180,
    images: ['https://images.unsplash.com/photo-1631451095765-2c91616fc9e6?auto=format&fit=crop&w=800&q=80'],
    tags: ['ghee', 'dairy', 'purity', 'cooking'],
  },
  {
    name: 'Fresh Cottage Cheese Paneer Block (200g)',
    slug: 'fresh-cottage-cheese-paneer-200g',
    description: 'Soft, velvety fresh cottage cheese made from 100% pure cow milk. High in protein for curries and grills.',
    price: 110,
    discountPrice: 89,
    stock: 180,
    brand: 'Dairy Pure',
    category: 'Dairy & Eggs',
    unit: '200g Pack',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 320,
    images: ['https://images.unsplash.com/photo-1631451095765-2c91616fc9e6?auto=format&fit=crop&w=800&q=80'],
    tags: ['paneer', 'cheese', 'dairy', 'protein'],
  },
  {
    name: 'Salted Creamery Cooking Butter Slab (500g)',
    slug: 'salted-creamery-cooking-butter-500g',
    description: 'Rich creamy butter made from pure fresh pasteurized milk. Essential for baking, cooking, and toast.',
    price: 290,
    discountPrice: 255,
    stock: 140,
    brand: 'Dairy Pure',
    category: 'Dairy & Eggs',
    unit: '500g Pack',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 260,
    images: ['https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=800&q=80'],
    tags: ['butter', 'dairy', 'cooking'],
  },
  {
    name: 'Greek Yogurt Alphonso Mango Flavor (400g Tub)',
    slug: 'greek-yogurt-alphonso-mango-400g',
    description: 'Thick strained high protein Greek yogurt blended with real mango fruit puree. Probiotic rich health snack.',
    price: 180,
    discountPrice: 145,
    stock: 100,
    brand: 'Dairy Pure',
    category: 'Dairy & Eggs',
    unit: '400g Tub',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 115,
    images: ['https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=800&q=80'],
    tags: ['yogurt', 'greek yogurt', 'dairy', 'probiotic'],
  },
  {
    name: 'Shredded Mozzarella & Cheddar Pizza Cheese (200g)',
    slug: 'shredded-mozzarella-cheddar-pizza-cheese',
    description: 'Perfect stretch and golden melt cheese blend ideal for homemade pizzas, lasagnas, and cheesy toasts.',
    price: 240,
    discountPrice: 199,
    stock: 120,
    brand: 'Dairy Pure',
    category: 'Dairy & Eggs',
    unit: '200g Pouch',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 190,
    images: ['https://images.unsplash.com/photo-1552767059-ce182ead8c1b?auto=format&fit=crop&w=800&q=80'],
    tags: ['cheese', 'mozzarella', 'pizza', 'dairy'],
  },
  {
    name: 'Fresh Thick Matka Curd Dahi (500g)',
    slug: 'fresh-thick-matka-curd-dahi-500g',
    description: 'Naturally set thick curd with authentic mild tangy taste and rich probiotics for digestion.',
    price: 65,
    discountPrice: 49,
    stock: 220,
    brand: 'Dairy Pure',
    category: 'Dairy & Eggs',
    unit: '500g Tub',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 340,
    images: ['https://images.unsplash.com/photo-1571212515416-fef01fc43637?auto=format&fit=crop&w=800&q=80'],
    tags: ['curd', 'dahi', 'dairy', 'probiotic'],
  },
  {
    name: 'Unsweetened Organic Almond Milk (1 Litre)',
    slug: 'unsweetened-organic-almond-milk-1l',
    description: '100% plant-based lactose-free almond beverage enriched with Vitamin E and calcium. Zero added sugar.',
    price: 299,
    discountPrice: 229,
    stock: 80,
    brand: 'Organic Farm',
    category: 'Dairy & Eggs',
    unit: '1 Litre Tetra Pack',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.7,
    ratingCount: 95,
    images: ['https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=800&q=80'],
    tags: ['almond milk', 'vegan', 'dairy free', 'healthy'],
  },
  {
    name: 'Gourmet Processed Cheese Slices Pack (200g)',
    slug: 'gourmet-processed-cheese-slices-200g',
    description: 'Individually wrapped creamy cheese slices for burgers, sandwiches, and fast snacks.',
    price: 175,
    discountPrice: 139,
    stock: 150,
    brand: 'Dairy Pure',
    category: 'Dairy & Eggs',
    unit: '10 Slices Pack',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 165,
    images: ['https://images.unsplash.com/photo-1618160702438-9b02ab6515c9?auto=format&fit=crop&w=800&q=80'],
    tags: ['cheese', 'slices', 'dairy', 'sandwich'],
  },

  // -------------------------------------------------------------
  // 7. PERSONAL CARE & BEAUTY (10 Products)
  // -------------------------------------------------------------
  {
    name: 'GlowSkin Vitamin C Hydrating Face Wash (150ml)',
    slug: 'glowskin-vitamin-c-hydrating-face-wash',
    description: 'Dermatologically tested facial cleanser with Vitamin C & Niacinamide for instant skin brightening.',
    price: 399,
    discountPrice: 299,
    stock: 110,
    brand: 'GlowSkin',
    category: 'Personal Care & Beauty',
    unit: '150ml Pump Bottle',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 112,
    images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80'],
    tags: ['beauty', 'skincare', 'face wash', 'personal care'],
  },
  {
    name: 'Activated Charcoal Deep Cleanse Shampoo (300ml)',
    slug: 'activated-charcoal-deep-cleanse-shampoo',
    description: 'Removes scalp impurities, excess oil, and product buildup. Enriched with Argan oil for silky smooth hair.',
    price: 449,
    discountPrice: 349,
    stock: 80,
    brand: 'HerbalPure',
    category: 'Personal Care & Beauty',
    unit: '300ml Bottle',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.7,
    ratingCount: 78,
    images: ['https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=800&q=80'],
    tags: ['shampoo', 'haircare', 'charcoal', 'personal care'],
  },
  {
    name: 'Ocean Breeze Refreshing Body Wash Gel (250ml)',
    slug: 'ocean-breeze-refreshing-body-wash-250ml',
    description: 'Enriched with sea minerals and aloe vera extract. Creates rich foaming lather with long-lasting freshness.',
    price: 349,
    discountPrice: 249,
    stock: 130,
    brand: 'GlowSkin',
    category: 'Personal Care & Beauty',
    unit: '250ml Bottle',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 92,
    images: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80'],
    tags: ['body wash', 'shower gel', 'personal care'],
  },
  {
    name: 'Pure Tea Tree Anti-Acne Facial Serum (30ml)',
    slug: 'pure-tea-tree-anti-acne-facial-serum',
    description: 'Formulated with 2% Salicylic Acid and Australian Tea Tree oil to control breakouts and clarify pores.',
    price: 599,
    discountPrice: 429,
    stock: 90,
    brand: 'GlowSkin',
    category: 'Personal Care & Beauty',
    unit: '30ml Dropper Bottle',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 140,
    images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80'],
    tags: ['serum', 'skincare', 'tea tree', 'acne'],
  },
  {
    name: 'Ultra Shield SPF 50 PA++++ Sunscreen Aqua Gel (80g)',
    slug: 'ultra-shield-spf-50-sunscreen-aqua-gel',
    description: 'Lightweight invisible gel formula with zero white cast. Protects skin from UVA/UVB rays and blue light.',
    price: 499,
    discountPrice: 379,
    stock: 150,
    brand: 'GlowSkin',
    category: 'Personal Care & Beauty',
    unit: '80g Tube',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 280,
    images: ['https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=800&q=80'],
    tags: ['sunscreen', 'spf 50', 'skincare', 'personal care'],
  },
  {
    name: 'Raw Shea Butter Deep Moisture Body Lotion (200ml)',
    slug: 'raw-shea-butter-deep-moisture-body-lotion',
    description: 'Nourishing ultra-hydrating lotion for dry skin with Vitamin E and organic African shea butter.',
    price: 399,
    discountPrice: 289,
    stock: 120,
    brand: 'HerbalPure',
    category: 'Personal Care & Beauty',
    unit: '200ml Bottle',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.7,
    ratingCount: 105,
    images: ['https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80'],
    tags: ['lotion', 'body care', 'shea butter', 'skincare'],
  },
  {
    name: 'Neem & Tea Tree Clarifying Face Scrub (100g)',
    slug: 'neem-and-tea-tree-clarifying-face-scrub',
    description: 'Exfoliates dead skin cells and unlogs blackheads with natural walnut shell particles and neem extract.',
    price: 299,
    discountPrice: 219,
    stock: 100,
    brand: 'HerbalPure',
    category: 'Personal Care & Beauty',
    unit: '100g Tube',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.6,
    ratingCount: 74,
    images: ['https://images.unsplash.com/photo-1567928269937-ae146e45b428?auto=format&fit=crop&w=800&q=80'],
    tags: ['face scrub', 'exfoliator', 'neem', 'skincare'],
  },
  {
    name: 'Argan Oil Hair Repairing Conditioner (250ml)',
    slug: 'argan-oil-hair-repairing-conditioner',
    description: 'Deeply conditions frizz and restores shine with Moroccan Argan oil and keratin protein.',
    price: 429,
    discountPrice: 329,
    stock: 95,
    brand: 'HerbalPure',
    category: 'Personal Care & Beauty',
    unit: '250ml Bottle',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 88,
    images: ['https://images.unsplash.com/photo-1526947425960-945c6e72858f?auto=format&fit=crop&w=800&q=80'],
    tags: ['conditioner', 'haircare', 'argan oil'],
  },
  {
    name: 'Herbal Toothpaste Fresh Mint Protection (150g)',
    slug: 'herbal-toothpaste-fresh-mint-protection',
    description: 'Natural fluoride-free toothpaste enriched with clove, neem, and fresh peppermint for complete cavity protection.',
    price: 140,
    discountPrice: 99,
    stock: 210,
    brand: 'HerbalPure',
    category: 'Personal Care & Beauty',
    unit: '150g Tube',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 180,
    images: ['https://images.unsplash.com/photo-1559598467-f8b76c8155d0?auto=format&fit=crop&w=800&q=80'],
    tags: ['toothpaste', 'oral care', 'herbal'],
  },
  {
    name: 'Eco-Friendly Charcoal Soft Bamboo Toothbrush Pack of 4',
    slug: 'eco-friendly-charcoal-bamboo-toothbrush-4pack',
    description: '100% biodegradable natural bamboo handles infused with active charcoal bristles for gentle gum cleaning.',
    price: 299,
    discountPrice: 199,
    stock: 140,
    brand: 'HerbalPure',
    category: 'Personal Care & Beauty',
    unit: '4 Pack',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 155,
    images: ['https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?auto=format&fit=crop&w=800&q=80'],
    tags: ['toothbrush', 'bamboo', 'eco friendly', 'oral care'],
  },

  // -------------------------------------------------------------
  // 8. HOME & KITCHEN (10 Products)
  // -------------------------------------------------------------
  {
    name: 'ProChef Non-Stick Die-Cast Frying Pan (26cm)',
    slug: 'prochef-non-stick-frying-pan-26cm',
    description: 'Heavy duty 5-layer granite coating, induction compatible base with ergonomic soft-touch handle.',
    price: 1899,
    discountPrice: 1299,
    stock: 45,
    brand: 'ProChef',
    category: 'Home & Kitchen',
    unit: '1 Pan',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.7,
    ratingCount: 58,
    images: ['https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80'],
    tags: ['kitchen', 'cookware', 'home', 'nonstick'],
  },
  {
    name: 'Stainless Steel Insulated Vacuum Water Bottle (1 Litre)',
    slug: 'stainless-steel-insulated-vacuum-water-bottle-1l',
    description: 'Keeps drinks ice cold for 24 hours or hot for 12 hours. BPA-free leakproof lid for office & gym.',
    price: 999,
    discountPrice: 699,
    stock: 140,
    brand: 'HydroSteel',
    category: 'Home & Kitchen',
    unit: '1 Bottle',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 165,
    images: ['https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=800&q=80'],
    tags: ['water bottle', 'kitchen', 'home', 'insulated'],
  },
  {
    name: 'Airtight Borosilicate Glass Meal Container Set (Set of 4)',
    slug: 'airtight-glass-meal-container-set-of-4',
    description: 'Oven & microwave safe borosilicate glass storage boxes with leakproof snap locking lids.',
    price: 1499,
    discountPrice: 1099,
    stock: 80,
    brand: 'ProChef',
    category: 'Home & Kitchen',
    unit: 'Set of 4 Containers',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 120,
    images: ['https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=800&q=80'],
    tags: ['glass container', 'kitchen', 'home', 'storage'],
  },
  {
    name: 'Smart Precision Digital Kitchen Food Scale (5kg)',
    slug: 'smart-precision-digital-kitchen-scale',
    description: 'High precision strain gauge sensor measures down to 1g accurately with LCD tare function display.',
    price: 899,
    discountPrice: 549,
    stock: 110,
    brand: 'ProChef',
    category: 'Home & Kitchen',
    unit: '1 Scale',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.7,
    ratingCount: 95,
    images: ['https://images.unsplash.com/photo-1590794056226-77ef3a6c4743?auto=format&fit=crop&w=800&q=80'],
    tags: ['kitchen scale', 'digital scale', 'home'],
  },
  {
    name: 'Microfiber Super Absorbent Cleaning Towels (Pack of 6)',
    slug: 'microfiber-super-absorbent-cleaning-towels-6pack',
    description: 'Lint-free non-scratching ultra absorbent cloths for kitchen countertops, glass, and dishes.',
    price: 399,
    discountPrice: 249,
    stock: 180,
    brand: 'ProChef',
    category: 'Home & Kitchen',
    unit: '6 Towels Pack',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 160,
    images: ['https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?auto=format&fit=crop&w=800&q=80'],
    tags: ['microfiber', 'cleaning', 'home', 'kitchen'],
  },
  {
    name: 'Heavy Duty Eco Bamboo Cutting Board with Knife Groove',
    slug: 'heavy-duty-bamboo-cutting-board',
    description: '100% natural organic bamboo chopping board with juice groove edge and knife-friendly surface.',
    price: 799,
    discountPrice: 499,
    stock: 90,
    brand: 'ProChef',
    category: 'Home & Kitchen',
    unit: '1 Board',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 140,
    images: ['https://images.unsplash.com/photo-1594385208974-2e75f8d7bb48?auto=format&fit=crop&w=800&q=80'],
    tags: ['chopping board', 'bamboo', 'kitchen', 'home'],
  },
  {
    name: 'Electric Fast Boiling Stainless Steel Kettle (1.5L)',
    slug: 'electric-fast-boiling-stainless-kettle-1-5l',
    description: '1500W rapid boil technology with automatic shutoff and dry boil protection safety system.',
    price: 1599,
    discountPrice: 1099,
    stock: 75,
    brand: 'VoltCharge',
    category: 'Home & Kitchen',
    unit: '1 Kettle',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 175,
    images: ['https://images.unsplash.com/photo-1594212699903-ec8a3eca50f6?auto=format&fit=crop&w=800&q=80'],
    tags: ['electric kettle', 'kitchen', 'home', 'appliance'],
  },
  {
    name: 'Automatic Touchless Motion Sensor Liquid Soap Dispenser',
    slug: 'automatic-touchless-soap-dispenser',
    description: 'Infrared sensor dispenses liquid soap in 0.2 seconds without physical contact for hygienic handwashing.',
    price: 1199,
    discountPrice: 799,
    stock: 65,
    brand: 'ProChef',
    category: 'Home & Kitchen',
    unit: '1 Unit',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.6,
    ratingCount: 80,
    images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80'],
    tags: ['soap dispenser', 'touchless', 'home', 'kitchen'],
  },
  {
    name: 'Ceramic Minimalist White Dinner Plate Set (Set of 6)',
    slug: 'ceramic-minimalist-white-dinner-plate-set',
    description: 'Microwave and dishwasher safe stoneware ceramic plates with elegant scratch-resistant matte glaze.',
    price: 2499,
    discountPrice: 1799,
    stock: 50,
    brand: 'ProChef',
    category: 'Home & Kitchen',
    unit: 'Set of 6 Plates',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 110,
    images: ['https://images.unsplash.com/photo-1614088685112-0a760b71a3c8?auto=format&fit=crop&w=800&q=80'],
    tags: ['dinnerware', 'plates', 'ceramic', 'kitchen'],
  },
  {
    name: 'Heat Resistant Non-Stick Silicone Kitchen Utensil Set',
    slug: 'heat-resistant-silicone-kitchen-utensil-set',
    description: 'Set of 10 BPA-free heat-resistant silicone spatulas, turners, and tongs with sturdy natural wooden handles.',
    price: 1399,
    discountPrice: 949,
    stock: 85,
    brand: 'ProChef',
    category: 'Home & Kitchen',
    unit: 'Set of 10 Utensils',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 130,
    images: ['https://images.unsplash.com/photo-1590794056226-77ef3a6c4743?auto=format&fit=crop&w=800&q=80'],
    tags: ['utensils', 'silicone', 'kitchen', 'home'],
  },

  // -------------------------------------------------------------
  // 9. BAKERY (10 Products)
  // -------------------------------------------------------------
  {
    name: 'Artisan Whole Wheat Garlic Bread Loaf (400g)',
    slug: 'artisan-whole-wheat-garlic-bread-loaf',
    description: 'Freshly baked whole grain loaf infused with roasted garlic, herbs, and pure butter crust.',
    price: 99,
    discountPrice: 79,
    stock: 65,
    brand: 'BakeHouse',
    category: 'Bakery',
    unit: '400g Loaf',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.7,
    ratingCount: 92,
    images: ['https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80'],
    tags: ['bread', 'bakery', 'garlic bread', 'fresh'],
  },
  {
    name: 'Classic Golden French Butter Croissants (Pack of 4)',
    slug: 'classic-golden-french-butter-croissants',
    description: 'Flaky multi-layered puff pastry baked daily with real French butter. Crisp outside and soft inside.',
    price: 240,
    discountPrice: 189,
    stock: 70,
    brand: 'BakeHouse',
    category: 'Bakery',
    unit: '4 Pack',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 140,
    images: ['https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=80'],
    tags: ['croissant', 'bakery', 'french', 'pastry'],
  },
  {
    name: 'Soft Multigrain Sandwich Bread Loaf (400g)',
    slug: 'soft-multigrain-sandwich-bread-loaf',
    description: 'Baked with flaxseeds, sunflower seeds, oats, and whole wheat. High in fiber and low in sugar.',
    price: 65,
    discountPrice: 49,
    stock: 120,
    brand: 'BakeHouse',
    category: 'Bakery',
    unit: '400g Loaf',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 210,
    images: ['https://images.unsplash.com/photo-1549931319-a545dcf3bc73?auto=format&fit=crop&w=800&q=80'],
    tags: ['bread', 'sandwich bread', 'multigrain', 'bakery'],
  },
  {
    name: 'Fudge Dark Chocolate Gourmet Brownies (Pack of 6)',
    slug: 'fudge-dark-chocolate-brownies-6pack',
    description: 'Rich gooey dark chocolate brownies baked with dark cocoa chunks and real butter.',
    price: 299,
    discountPrice: 229,
    stock: 80,
    brand: 'BakeHouse',
    category: 'Bakery',
    unit: '6 Pieces Box',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 175,
    images: ['https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80'],
    tags: ['brownie', 'chocolate', 'dessert', 'bakery'],
  },
  {
    name: 'Freshly Baked Belgian Sugar Waffles (Pack of 2)',
    slug: 'freshly-baked-belgian-waffles-2pack',
    description: 'Golden Liege style Belgian waffles with caramelized pearl sugar pockets inside.',
    price: 150,
    discountPrice: 119,
    stock: 90,
    brand: 'BakeHouse',
    category: 'Bakery',
    unit: '2 Waffles Pack',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.7,
    ratingCount: 110,
    images: ['https://images.unsplash.com/photo-1562376552-0d160a2f238d?auto=format&fit=crop&w=800&q=80'],
    tags: ['waffles', 'belgian waffles', 'bakery'],
  },
  {
    name: 'Rustic Italian Olive & Herb Ciabatta Loaf (300g)',
    slug: 'rustic-italian-olive-herb-ciabatta',
    description: 'Sourdough fermented Italian crusty bread loaded with black olives and oregano herbs.',
    price: 120,
    discountPrice: 89,
    stock: 60,
    brand: 'BakeHouse',
    category: 'Bakery',
    unit: '300g Loaf',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 68,
    images: ['https://images.unsplash.com/photo-1586444248902-2f64eddc13df?auto=format&fit=crop&w=800&q=80'],
    tags: ['ciabatta', 'bread', 'italian', 'bakery'],
  },
  {
    name: 'Soft Cinnamon Swirl Rolls with Vanilla Frosting (4 Pack)',
    slug: 'cinnamon-swirl-rolls-vanilla-frosting-4pack',
    description: 'Warm fluffy cinnamon rolls layered with Saigon cinnamon and cream cheese vanilla drizzle.',
    price: 220,
    discountPrice: 169,
    stock: 75,
    brand: 'BakeHouse',
    category: 'Bakery',
    unit: '4 Pack',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 130,
    images: ['https://images.unsplash.com/photo-1509365465985-25d11c17e812?auto=format&fit=crop&w=800&q=80'],
    tags: ['cinnamon rolls', 'pastry', 'bakery'],
  },
  {
    name: 'Classic Moist Vanilla Tea Cake (350g)',
    slug: 'classic-moist-vanilla-tea-cake-350g',
    description: 'Soft buttery vanilla sponge cake cooked with real Madagascar vanilla pod extract.',
    price: 180,
    discountPrice: 139,
    stock: 85,
    brand: 'BakeHouse',
    category: 'Bakery',
    unit: '350g Loaf',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.7,
    ratingCount: 95,
    images: ['https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80'],
    tags: ['tea cake', 'cake', 'vanilla', 'bakery'],
  },
  {
    name: 'Crunchy Chocolate Chip Handmade Cookies (250g Box)',
    slug: 'crunchy-chocolate-chip-handmade-cookies',
    description: 'Golden oven-baked crispy butter cookies packed with dark chocolate chips.',
    price: 199,
    discountPrice: 149,
    stock: 110,
    brand: 'BakeHouse',
    category: 'Bakery',
    unit: '250g Box',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 160,
    images: ['https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=800&q=80'],
    tags: ['cookies', 'chocolate chip', 'bakery'],
  },
  {
    name: 'Everything Sesame & Poppy Seed Hand-Rolled Bagels (4 Pack)',
    slug: 'everything-sesame-poppy-bagels-4pack',
    description: 'Authentic New York style chewy bagels coated in roasted sesame, poppy seeds, garlic, and onion flakes.',
    price: 180,
    discountPrice: 139,
    stock: 70,
    brand: 'BakeHouse',
    category: 'Bakery',
    unit: '4 Bagels Pack',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 85,
    images: ['https://images.unsplash.com/photo-1585478259715-876acc5be8eb?auto=format&fit=crop&w=800&q=80'],
    tags: ['bagels', 'bread', 'bakery'],
  },

  // -------------------------------------------------------------
  // 10. PANTRY & OIL (10 Products)
  // -------------------------------------------------------------
  {
    name: 'Extra Virgin Cold Pressed Olive Oil (750ml)',
    slug: 'extra-virgin-cold-pressed-olive-oil-750ml',
    description: 'First cold-pressed Mediterranean olive oil rich in antioxidants and healthy monounsaturated fats.',
    price: 1199,
    discountPrice: 899,
    stock: 70,
    brand: 'Mediterraneo',
    category: 'Pantry & Oil',
    unit: '750ml Glass Bottle',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 195,
    images: ['https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=800&q=80'],
    tags: ['olive oil', 'pantry', 'cooking', 'healthy'],
  },
  {
    name: 'Royal Aged Long Grain Basmati Rice (5kg Bag)',
    slug: 'royal-aged-long-grain-basmati-rice-5kg',
    description: 'Aged for 2 years for extra-long fluffy grains and delicate royal aromatic fragrance.',
    price: 899,
    discountPrice: 699,
    stock: 140,
    brand: 'Mediterraneo',
    category: 'Pantry & Oil',
    unit: '5kg Cloth Bag',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 380,
    images: ['https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80'],
    tags: ['rice', 'basmati', 'pantry', 'grains'],
  },
  {
    name: 'Pure Himalayan Organic Pink Rock Salt (1kg Pouch)',
    slug: 'pure-himalayan-organic-pink-salt-1kg',
    description: 'Unrefined mineral-rich pink salt mined directly from ancient Himalayan foothills. Contains 84 trace minerals.',
    price: 149,
    discountPrice: 99,
    stock: 250,
    brand: 'Mediterraneo',
    category: 'Pantry & Oil',
    unit: '1kg Pouch',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 290,
    images: ['https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800&q=80'],
    tags: ['salt', 'pink salt', 'himalayan', 'pantry'],
  },
  {
    name: 'Cold Pressed Unrefined Virgin Coconut Oil (500ml)',
    slug: 'cold-pressed-unrefined-virgin-coconut-oil',
    description: 'Extracted from raw fresh coconut milk. Ideal for healthy cooking, keto diets, hair, and skin moisture.',
    price: 399,
    discountPrice: 299,
    stock: 110,
    brand: 'Organic Farm',
    category: 'Pantry & Oil',
    unit: '500ml Glass Jar',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 165,
    images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80'],
    tags: ['coconut oil', 'oil', 'pantry', 'healthy'],
  },
  {
    name: 'Whole Tellicherry Black Peppercorns Grinder (100g)',
    slug: 'whole-tellicherry-black-peppercorns-grinder',
    description: 'Jumbo dark pepper berries from Malabar coast in a ceramic adjustable built-in mill grinder.',
    price: 299,
    discountPrice: 219,
    stock: 90,
    brand: 'Mediterraneo',
    category: 'Pantry & Oil',
    unit: '100g Grinder Bottle',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 105,
    images: ['https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=800&q=80'],
    tags: ['black pepper', 'spices', 'pantry'],
  },
  {
    name: 'Raw Organic Wildflower Forest Honey (500g Glass Jar)',
    slug: 'raw-organic-wildflower-forest-honey-500g',
    description: 'Unprocessed 100% pure raw honey harvested from natural forest beehives. Rich in enzymes and pollen.',
    price: 499,
    discountPrice: 379,
    stock: 130,
    brand: 'Organic Farm',
    category: 'Pantry & Oil',
    unit: '500g Jar',
    isFeatured: true,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 220,
    images: ['https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=800&q=80'],
    tags: ['honey', 'organic', 'raw honey', 'pantry'],
  },
  {
    name: 'Whole Grain 100% Chakki Fresh Multigrain Atta (5kg)',
    slug: 'whole-grain-chakki-fresh-multigrain-atta-5kg',
    description: 'Traditional stone ground wheat flour mixed with soya, chana, oats, maize, and psyllium husk.',
    price: 380,
    discountPrice: 319,
    stock: 160,
    brand: 'Organic Farm',
    category: 'Pantry & Oil',
    unit: '5kg Pack',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.8,
    ratingCount: 310,
    images: ['https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=800&q=80'],
    tags: ['atta', 'wheat', 'flour', 'pantry'],
  },
  {
    name: 'Durum Wheat Semolina Penne Rigate Pasta (500g)',
    slug: 'durum-wheat-penne-rigate-pasta-500g',
    description: 'Bronze-die extruded 100% Italian durum wheat semolina pasta. Holds sauces perfectly al dente.',
    price: 199,
    discountPrice: 149,
    stock: 120,
    brand: 'Mediterraneo',
    category: 'Pantry & Oil',
    unit: '500g Pack',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.7,
    ratingCount: 140,
    images: ['https://images.unsplash.com/photo-1551462147-ff29053bfc14?auto=format&fit=crop&w=800&q=80'],
    tags: ['pasta', 'penne', 'italian', 'pantry'],
  },
  {
    name: 'Cold Pressed Kachi Ghani Mustard Oil (1 Litre Bottle)',
    slug: 'cold-pressed-kachi-ghani-mustard-oil-1l',
    description: 'Pure mustard oil pressed at low temperature to retain natural pungency, aroma, and omega-3 fatty acids.',
    price: 220,
    discountPrice: 179,
    stock: 180,
    brand: 'Organic Farm',
    category: 'Pantry & Oil',
    unit: '1 Litre Bottle',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 260,
    images: ['https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=800&q=80'],
    tags: ['mustard oil', 'cooking oil', 'pantry'],
  },
  {
    name: 'Organic Turmeric Powder Haldi High Curcumin (200g)',
    slug: 'organic-turmeric-powder-haldi-200g',
    description: 'Pure Lakadong turmeric powder with 5%+ active curcumin content for immunity and cooking.',
    price: 160,
    discountPrice: 119,
    stock: 200,
    brand: 'Organic Farm',
    category: 'Pantry & Oil',
    unit: '200g Pack',
    isFeatured: false,
    isPublished: true,
    ratingAverage: 4.9,
    ratingCount: 210,
    images: ['https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800&q=80'],
    tags: ['turmeric', 'haldi', 'spices', 'pantry'],
  },
];

async function seedDatabase() {
  try {
    console.log('Connecting to MongoDB...');
    await mongoose.connect(MONGODB_URI);
    console.log('Connected to MongoDB.');

    console.log('Clearing old users and products...');
    await User.deleteMany({});
    await Product.deleteMany({});

    console.log('Creating initial users...');
    const createdUsers = await User.create(sampleUsers);
    const adminUser = createdUsers.find((u) => u.role === 'admin');

    console.log(`Admin user created: ${adminUser.email}`);

    console.log(`Creating ${sampleProducts.length} multi-category products...`);
    const productsToInsert = sampleProducts.map((p) => ({
      ...p,
      createdBy: adminUser._id,
    }));

    await Product.create(productsToInsert);
    console.log(`Successfully seeded ${productsToInsert.length} multi-category products!`);

    console.log('\n--- SEED COMPLETE ---');
    console.log('Total Products Seeded:', productsToInsert.length);
    console.log('Admin Login: admin@grocery.com / Password@123');
    console.log('User Login: user@grocery.com / Password@123');
    console.log('--------------------\n');

    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
}

seedDatabase();
